name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  push_to_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get tag
      id: tag
      uses: devops-actions/action-get-tag@v1.0.1
      with:
        strip_v: true # Optional: Remove 'v' character from version
        default: v7.2.0 # Optional: Default version when tag not found
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
          repository: tackacoder/php
          push: true
          tags: ${{ steps.tag.outputs.tag }}
